[package]
authors.workspace      = true
description.workspace  = true
edition.workspace      = true
license.workspace      = true
name                   = "rustly-core"
publish                = false
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[dependencies]
rustly-core-domain  = { path = "./crates/domain" }
rustly-core-gateway = { path = "./crates/gateway" }

bumpalo.workspace       = true
ordered-float.workspace = true
rb-sys                  = { workspace = true, features = ["link-ruby", "stable-api"] }
serde.workspace         = true
serde_json.workspace    = true
smallvec.workspace      = true
thiserror.workspace     = true

[build-dependencies]
rb-sys-build = "0.9.117"

[profile.release]
codegen-units = 1
lto           = true
strip         = true
