[package]
authors      = ["dude <skuf@justregulardude.ru>"]
edition      = "2024"
license      = "MIT"
name         = "rustly-core"
publish      = false
rust-version = "1.90"
version      = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
bumpalo       = { version = "3.19.0", features = ["collections"] }
ordered-float = "5.1.0"
rb-sys        = { version = "0.9.117", features = ["link-ruby", "stable-api"] }
serde         = { version = "1.0.228", features = ["derive"] }
serde_json    = "1.0.145"
smallvec      = "1.13.2"
thiserror     = "2.0.17"

[build-dependencies]
rb-sys-build = "0.9.117"
