module Rustly
  module Core
    VERSION: String
    DEFAULT_OPTIONS: {
      strict: bool,
      extra: Symbol,
      input_mode: Symbol,
      freeze: Symbol,
      store_attributes: bool
    }

    def self.version: () -> String
    def self.native_compile: (untyped, Hash[Symbol, untyped]) -> Rustly::Core::CompiledSchema
    def self.compile: (untyped, ?Hash[Symbol | String, untyped]) -> Rustly::Core::CompiledSchema
    def self.native_build: (
      Rustly::Core::CompiledSchema,
      untyped,
      untyped
    ) -> untyped
    def self.build: (
      Rustly::Core::CompiledSchema,
      untyped,
      untyped
    ) -> untyped

    class CompiledSchema
      def id: () -> Integer
      def summary: () -> String
    end

    class ErrorSet
      def messages: () -> Array[Hash[String, untyped]]
      def to_a: () -> Array[Hash[String, untyped]]
    end
  end
end
